import { useNavigate } from "react-router-dom";
import { ArrowLeft, ShieldCheck, Trash2, Sun, Moon, User, LogOut } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useApp } from "@/lib/AppContext";
import { useTheme } from "@/hooks/use-theme";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export default function SettingsPage() {
  const navigate = useNavigate();
  const { resetAll } = useApp();
  const { theme, toggleTheme } = useTheme();

  const handleLogout = async () => {
    await supabase.auth.signOut();
    toast.success("Logged out!");
    navigate("/auth");
  };

  const handleReset = () => {
    if (confirm("Reset all progress? This cannot be undone.")) {
      resetAll();
      toast.success("All progress has been reset.");
      navigate("/");
    }
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-2xl mx-auto px-4 py-6">
        <button onClick={() => navigate(-1)} className="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground mb-6">
          <ArrowLeft className="w-4 h-4" /> Back
        </button>

        <h1 className="font-heading text-2xl font-bold text-foreground mb-8">Settings</h1>

        {/* Theme toggle */}
        <div className="bg-card border border-border rounded-xl p-6 mb-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-accent/10 flex items-center justify-center">
                {theme === "dark" ? <Moon className="w-5 h-5 text-accent" /> : <Sun className="w-5 h-5 text-warning" />}
              </div>
              <div>
                <h2 className="font-heading font-semibold text-foreground">Theme</h2>
                <p className="text-xs text-muted-foreground">{theme === "dark" ? "Dark mode" : "Light mode"}</p>
              </div>
            </div>
            <Button variant="outline" size="sm" onClick={toggleTheme}>
              {theme === "dark" ? <Sun className="w-4 h-4 mr-2" /> : <Moon className="w-4 h-4 mr-2" />}
              {theme === "dark" ? "Light" : "Dark"}
            </Button>
          </div>
        </div>

        {/* Profile link */}
        <button
          onClick={() => navigate("/profile")}
          className="w-full bg-card border border-border rounded-xl p-6 mb-6 flex items-center gap-3 hover:border-primary/30 transition-colors text-left"
        >
          <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
            <User className="w-5 h-5 text-primary" />
          </div>
          <div>
            <h2 className="font-heading font-semibold text-foreground">Edit Profile</h2>
            <p className="text-xs text-muted-foreground">Name, bio, avatar, social links</p>
          </div>
        </button>

        {/* AI security mode */}
        <div className="bg-card border border-border rounded-xl p-6 mb-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 rounded-lg bg-success/10 flex items-center justify-center">
              <ShieldCheck className="w-5 h-5 text-success" />
            </div>
            <div>
              <h2 className="font-heading font-semibold text-foreground">AI Security</h2>
              <p className="text-xs text-muted-foreground">Server-side AI mode is enabled</p>
            </div>
          </div>
          <p className="text-sm text-muted-foreground mb-4">
            Your roadmap, exams, and mentor chat are generated by secure backend functions. The AI provider key is kept server-side and is not exposed to the browser.
          </p>
          <p className="text-[10px] text-muted-foreground">If AI generation fails, verify your Supabase Edge Function deployment and secrets.</p>
        </div>

        {/* Danger zone */}
        <div className="bg-card border border-destructive/30 rounded-xl p-6">
          <h2 className="font-heading font-semibold text-destructive mb-2">Danger Zone</h2>
          <p className="text-sm text-muted-foreground mb-4">Reset all progress, roadmaps, and achievements. This action cannot be undone.</p>
          <Button variant="destructive" onClick={handleReset}>
            <Trash2 className="w-4 h-4 mr-2" /> Reset All Progress
          </Button>
        </div>

        {/* Logout */}
        <Button variant="outline" onClick={handleLogout} className="w-full mt-6 border-border">
          <LogOut className="w-4 h-4 mr-2" /> Sign Out
        </Button>
      </div>
    </div>
  );
}
